package db

import (
	"database/sql"
	"fmt"
	"time"

	_ "github.com/sijms/go-ora/v2"
)

// Database handles connection and queries to Oracle DB
type Database struct {
	db *sql.DB
}

// ThumbnailRecord represents a record in the database
type ThumbnailRecord struct {
	ID           int64
	OriginalURL  string
	ThumbnailURL string
	CreatedAt    time.Time
}

// NewDatabase creates a new Oracle database connection
// dsn should be in the format: oracle://user:password@host:port/service
func NewDatabase(dsn string) (*Database, error) {
	db, err := sql.Open("oracle", dsn)
	if err != nil {
		return nil, fmt.Errorf("failed to open database: %w", err)
	}

	if err := db.Ping(); err != nil {
		return nil, fmt.Errorf("failed to ping database: %w", err)
	}

	return &Database{db: db}, nil
}

// InitSchema creates the image table if it doesn't exist
func (d *Database) InitSchema() error {
	query := `
	DECLARE
		v_count NUMBER;
	BEGIN
		SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'IMAGE';
		IF v_count = 0 THEN
			EXECUTE IMMEDIATE '
				CREATE TABLE image (
					id                 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					original_url       VARCHAR2(512)  NOT NULL,
					thumbnail_url      VARCHAR2(512),
					uploader_id        NUMBER(19),
					created_at         TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
					object_key         VARCHAR2(200),
					encrypted_key      VARCHAR2(512),
					CONSTRAINT fk_image_uploader FOREIGN KEY (uploader_id) REFERENCES service_user (id)
				)
			';
		END IF;
	END;`

	_, err := d.db.Exec(query)
	if err != nil {
		return fmt.Errorf("failed to init schema: %w", err)
	}
	return nil
}

// UpdateThumbnail updates the thumbnail URL and object key for an existing image record
func (d *Database) UpdateThumbnail(id int64, thumbnailURL string, objectKey string) error {
	query := `UPDATE IMAGE SET thumbnail_url = :1, object_key = :2 WHERE id = :3`

	result, err := d.db.Exec(query, thumbnailURL, objectKey, id)
	if err != nil {
		return fmt.Errorf("failed to update thumbnail record: %w", err)
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("failed to get rows affected: %w", err)
	}
	if rowsAffected == 0 {
		return fmt.Errorf("no record found with ID %d", id)
	}

	return nil
}

// GetImageInfo fetches the original URL, original object key, encrypted KMS key, and thumbnail URL for an image
func (d *Database) GetImageInfo(id int64) (string, sql.NullString, sql.NullString, sql.NullString, error) {
	query := `SELECT original_url, object_key, encrypted_key, thumbnail_url FROM image WHERE id = :1`

	var originalURL string
	var objectKey sql.NullString
	var encryptedKey sql.NullString
	var thumbnailURL sql.NullString

	err := d.db.QueryRow(query, id).Scan(&originalURL, &objectKey, &encryptedKey, &thumbnailURL)
	if err != nil {
		if err == sql.ErrNoRows {
			return "", sql.NullString{}, sql.NullString{}, sql.NullString{}, fmt.Errorf("no record found with ID %d", id)
		}
		return "", sql.NullString{}, sql.NullString{}, sql.NullString{}, fmt.Errorf("failed to query image info: %w", err)
	}

	return originalURL, objectKey, encryptedKey, thumbnailURL, nil
}

// GetPendingThumbnails fetches IDs of images that are missing thumbnails and are older than 5 minutes
func (d *Database) GetPendingThumbnails(limit int) ([]int64, error) {
	query := `SELECT id FROM image WHERE thumbnail_url IS NULL AND created_at < CURRENT_TIMESTAMP - INTERVAL '5' MINUTE FETCH FIRST :1 ROWS ONLY`
	
	rows, err := d.db.Query(query, limit)
	if err != nil {
		return nil, fmt.Errorf("failed to query pending thumbnails: %w", err)
	}
	defer rows.Close()

	var ids []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, fmt.Errorf("failed to scan id: %w", err)
		}
		ids = append(ids, id)
	}
	
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("row iteration error: %w", err)
	}

	return ids, nil
}

// Close closes the database connection
func (d *Database) Close() error {
	return d.db.Close()
}

// GetImageInfoByObjectKey fetches the original URL, original object key, encrypted KMS key, and thumbnail URL for an image by object key
func (d *Database) GetImageInfoByObjectKey(objectKey string) (string, sql.NullString, sql.NullString, sql.NullString, error) {
	query := `SELECT original_url, object_key, encrypted_key, thumbnail_url FROM image WHERE object_key = :1`

	var originalURL string
	var objKey sql.NullString
	var encryptedKey sql.NullString
	var thumbnailURL sql.NullString

	err := d.db.QueryRow(query, objectKey).Scan(&originalURL, &objKey, &encryptedKey, &thumbnailURL)
	if err != nil {
		if err == sql.ErrNoRows {
			return "", sql.NullString{}, sql.NullString{}, sql.NullString{}, fmt.Errorf("no record found with object_key %s", objectKey)
		}
		return "", sql.NullString{}, sql.NullString{}, sql.NullString{}, fmt.Errorf("failed to query image info: %w", err)
	}

	return originalURL, objKey, encryptedKey, thumbnailURL, nil
}
