package db

import (
	"database/sql"
	"fmt"
	"time"

	_ "github.com/sijms/go-ora/v2"
)

// Database handles connection and queries to Oracle DB
type Database struct {
	db *sql.DB
}

// ThumbnailRecord represents a record in the database
type ThumbnailRecord struct {
	ID           int64
	OriginalURL  string
	ThumbnailURL string
	CreatedAt    time.Time
}

// NewDatabase creates a new Oracle database connection
// dsn should be in the format: oracle://user:password@host:port/service
func NewDatabase(dsn string) (*Database, error) {
	db, err := sql.Open("oracle", dsn)
	if err != nil {
		return nil, fmt.Errorf("failed to open database: %w", err)
	}

	if err := db.Ping(); err != nil {
		return nil, fmt.Errorf("failed to ping database: %w", err)
	}

	return &Database{db: db}, nil
}

// InitSchema creates the image table if it doesn't exist
func (d *Database) InitSchema() error {
	query := `
	DECLARE
		v_count NUMBER;
	BEGIN
		SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'IMAGE';
		IF v_count = 0 THEN
			EXECUTE IMMEDIATE '
				CREATE TABLE image (
					id                 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					original_url       VARCHAR2(512)  NOT NULL,
					thumbnail_url      VARCHAR2(512),
					uploader_id        NUMBER(19),
					created_at         TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL
				)
			';
		END IF;
	END;`

	_, err := d.db.Exec(query)
	if err != nil {
		return fmt.Errorf("failed to init schema: %w", err)
	}
	return nil
}

// UpdateThumbnail updates the thumbnail URL for an existing image record
func (d *Database) UpdateThumbnail(id int64, thumbnailURL string) error {
	query := `UPDATE IMAGE SET thumbnail_url = :1 WHERE id = :2`

	result, err := d.db.Exec(query, thumbnailURL, id)
	if err != nil {
		return fmt.Errorf("failed to update thumbnail record: %w", err)
	}
	
	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("failed to get rows affected: %w", err)
	}
	if rowsAffected == 0 {
		return fmt.Errorf("no record found with ID %d", id)
	}

	return nil
}

// Close closes the database connection
func (d *Database) Close() error {
	return d.db.Close()
}
