name: Deploy to OCI Compute

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.x'
        cache: true

    - name: Build Go binary for Linux
      run: |
        GOOS=linux GOARCH=amd64 go build -v -o thumbnailer main.go

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        # HEREDOC prevents newline issues with private keys
        cat << 'EOF' > ~/.ssh/id_rsa
        ${{ secrets.SERVER_SSH_KEY }}
        EOF
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy binary via native SCP
      run: |
        scp -v -o StrictHostKeyChecking=no -o BatchMode=yes -i ~/.ssh/id_rsa thumbnailer ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/home/${{ secrets.SERVER_USERNAME }}/app/thumbnailer

    - name: Restart Systemd Service via native SSH
      run: |
        ssh -v -o StrictHostKeyChecking=no -o BatchMode=yes -i ~/.ssh/id_rsa ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "chmod +x /home/${{ secrets.SERVER_USERNAME }}/app/thumbnailer && sudo systemctl restart thumbnailer"
